# Copyright (C) 2014 Queensland Cyber Infrastructure Foundation (http://www.qcif.edu.au/)
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# 
# Author: <a href="https://github.com/shilob">Shilo Banihit</a>
 
HeatTemplateFormatVersion: '2012-12-12'

Description: >
  Template for creating a ReDBox-Mint software stack on ephemeral storage. 
  This template currently works only with the NeCTAR CentOS 6.5 x86_64 image. 
  Among others, useful in spinning up VMs for development or demonstration purposes.
  
Parameters:
  KeyName:
    Label: SSH Key Pair 
    Type: String
    Description:
      Name of an existing key pair to enable SSH access to the instance.
  InstanceSize:
    Label: Instance Size
    Type: String
    Description: Size of the instance to be created.
    Default: m1.small
    AllowedValues: [m1.small, m1.medium, m1.large, m1.xlarge, m1.xxlarge]
  ImageName:
    Label: OS Image
    Type: String
    Description: Name of the image to use for the instance to be created (currently only has support for CentOS)
    Default: NeCTAR CentOS 6.5 x86_64
    AllowedValues: [NeCTAR CentOS 6.5 x86_64]
  AvailabilityZone:
    Label: Availability Zone
    Type: String
    Description: The NeCTAR zone in which the VM is to run (must have block storage)
    Default: NCI
    AllowedValues: [melbourne,monash,sa, QRIScloud, tasmania, intersect, nova, NCI]
  InstallType:
    Label: Installation Type
    Type: String
    Description: The ReDBox Installation type, defaults to ‘basic’. 
    Default: basic
    AllowedValues: [basic, harvester-complete]
  PostInstallCmd:
    Label: Post Install Command
    Type: String
    Default: ls -l
    Description: A comma delimited list of bash commands to run after ReDBox is installed.
  CidrInstitution:
    Type: String
    Default: 0.0.0.0/0
    Description: The CIDR of the institution's network.
  CidrNla:
    Type: String
    Default: 0.0.0.0/0
    Description: The CIDR of NLA
  
Mappings:
  InstanceId:
   'NeCTAR CentOS 6.5 x86_64': {ImageId: a5e74703-f343-415a-aa23-bd0f0aacfc9e}   

Resources:
  ReDBoxSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Enable ReDBox Ports"
      SecurityGroupIngress:        
        -
          IpProtocol: "tcp"
          FromPort: "80"
          ToPort: "80"
          CidrIp: {Ref: CidrInstitution}
        -
          IpProtocol: "tcp"
          FromPort: "80"
          ToPort: "80"
          CidrIp: {Ref: CidrNla}
        -
          IpProtocol: "tcp"
          FromPort: "22"
          ToPort: "22"
          CidrIp: "0.0.0.0/0"
  ReDBoxInstance:
    Type: OS::Nova::Server
    Properties:
      availability_zone: { Ref: AvailabilityZone }
      image:
        Fn::FindInMap:
        - InstanceId
        - {Ref: ImageName}
        - ImageId
      flavor: { Ref: InstanceSize }
      key_name: { Ref: KeyName }
      security_groups: [{Ref: ReDBoxSecGroup}]
      user_data:
        Fn::Base64:
          Fn::Replace:
          - _InstallType: {Ref: InstallType}
            _PostInstallCmd: {Ref: PostInstallCmd}
          - |
            #!/bin/bash -v
            # Mount the Ephemeral disk and use it as /opt
            echo "Starting to install software stack..."
            echo `date +"%D-%H:%M:%S"`
            mkdir /mnt/ephemeral              
            echo "/dev/vdb        /mnt/ephemeral    auto    defaults,auto,nofail,comment=heatconfig     0       2" >> /etc/fstab              
            mount /mnt/ephemeral && mkdir /mnt/ephemeral/opt && rm -rf /opt && ln -s /mnt/ephemeral/opt /opt            
            # Install puppet and install ReDBox              
            mkdir -p /tmp/redbox
            wget -N -O /tmp/redbox/install.sh https://raw.githubusercontent.com/redbox-mint-contrib/puppet-redbox/master/scripts/install.sh 
            chmod +x /tmp/redbox/install.sh
            /tmp/redbox/install.sh _InstallType
            echo "ReDBox is installed."
            echo "Running Post Install Commands..."
            while IFS=',' read -ra POST_INSTALL_CMDS; do
                for cmd in "${POST_INSTALL_CMDS[@]}"; do
                  echo "Running... $cmd"
                  /bin/bash -c "$cmd"
                done
            done <<< "_PostInstallCmd"
            echo "Done Running Post Install Commands."
            echo "End of software stack installation"
            echo `date +"%D-%H:%M:%S"` 

Outputs:  
  MintURL:
    Description: The URL of Mint      
    Value:
      Fn::Join:
      - ''
      - - http://
        - Fn::GetAtt: [ReDBoxInstance, first_address]
        - /mint/default/home
  ReDBoxURL:
    Description: The URL of ReDBox      
    Value:
      Fn::Join:
      - ''
      - - http://
        - Fn::GetAtt: [ReDBoxInstance, first_address]
        - /redbox/default/home    
  InstanceIP:
    Description: Public IP address of the newly created ReDBox instance.
    Value:
      Fn::GetAtt:
      - ReDBoxInstance
      - first_address
